### ISSUE TITLE
Update run arguments and evironments

### ISSUE THREAD

**Issue by FelixKlauke** [FelixKlauke/paperspigot-docker#17]
We should update the readme in git and on docker hub regarding the configuration via arguments and environment.

**Comment by quorn23** [comment]
I was about to open a request for this, as it would be rather helpful to be able to assign the Min/max ram for the server. i assume this is what you mean with this issue?

**Comment by FelixKlauke** [comment]
Exactly. 

For your specific request: You can assign the ENV Variable `JAVA_HEAP_SIZE`, this will be the min and max RAM amount :)
