### ISSUE TITLE
Access to the server console

### ISSUE THREAD

**Issue by acs** [FelixKlauke/paperspigot-docker#49]
Is it possible to start the server from a screen so the server console could be accessed?

Something like:

`screen -dmS minecraft java -Xms512M -Xmx950M -jar spigot-1.15.2.jar`

Thanks @FelixKlauke for your great dockering work!

We are using it at: https://github.com/juntosdesdecasa/minecraft/tree/develop/server

**Comment by FelixKlauke** [comment]
Hey,

I'm happy to see my work can help you. You can access the console by attaching to the docker container, e.g.:

`docker attach minecraft`

If that isn't suitable for you you can consider using RCON.
