### ISSUE TITLE
DockerHub - Missing 1.16.1 tag

### ISSUE THREAD

**Issue by FrostiiZ** [FelixKlauke/paperspigot-docker#53]
As said in the title, the current most recent tag on GitHub is 1.16.1, but it haven't been added to DockerHub (most recent is 1.15.2), which makes me unable to update my container.
The "latest" tag is also a year old, which could be changed to 1.16.1.
The Markdown on DockerHub also misses the 1.15.2 tag in the "Tags and Versions" section.

(cf https://hub.docker.com/r/felixklauke/paperspigot)

Thank you for your great work, I've been using your image for a year now and I haven't encountered any issue related to your configuration.

**Comment by steelcowboy** [comment]
Hey @FelixKlauke, could you update that tag? It seems the repo has been ready for a few weeks now and really looking forward to getting my 1.16 server going :D

**Comment by Tockra** [comment]
Further this docker-compose file is buggy. But it shouldn't :
```bash
version: '3.7'

services:
  minecraft:
    build: ./
    container_name: minecraft
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 9415:25565
    volumes:
      - ./data/config/:/opt/minecraft/config
      - ./data/worlds/:/opt/minecraft/worlds
      - ./data/plugins/:/opt/minecraft/plugins
      - ./data/data/:/opt/minecraft/data
      - ./data/logs/:/opt/minecraft/logs
```

**Comment by Azratosh** [comment]
@Tockra This is due to [the way bind mounts behave.](https://docs.docker.com/storage/bind-mounts/#mount-into-a-non-empty-directory-on-the-container) Bind mounts are only recommended if you're already dockerizing an existing server. Otherwise, use volumes and transfer files from and to your container with [docker cp](https://docs.docker.com/engine/reference/commandline/cp/).

**Comment by FelixKlauke** [comment]
@FrostiiZ @steelcowboy Just triggered a release via #55, should be available on docker hub very soon :)
